/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:606168:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('1');
} //_CODE_:button1:606168:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:528561:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('a');
} //_CODE_:button2:528561:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:249446:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('2');
} //_CODE_:button3:249446:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:624513:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('b');
} //_CODE_:button4:624513:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:877722:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('3');
} //_CODE_:button5:877722:

public void button6_click1(GButton source, GEvent event) { //_CODE_:button6:718461:
  println("button6 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('c');
} //_CODE_:button6:718461:

public void button7_click1(GButton source, GEvent event) { //_CODE_:button7:554938:
  println("button7 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('4');
} //_CODE_:button7:554938:

public void button8_click1(GButton source, GEvent event) { //_CODE_:button8:489924:
  println("button8 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('d');
} //_CODE_:button8:489924:

public void button9_click1(GButton source, GEvent event) { //_CODE_:button9:979175:
  println("button9 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('5');
} //_CODE_:button9:979175:

public void button10_click1(GButton source, GEvent event) { //_CODE_:button10:380281:
  println("button10 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('e');
} //_CODE_:button10:380281:

public void button11_click1(GButton source, GEvent event) { //_CODE_:button11:256727:
  println("button11 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('6');
} //_CODE_:button11:256727:

public void button12_click1(GButton source, GEvent event) { //_CODE_:button12:890922:
  println("button12 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('f');
} //_CODE_:button12:890922:

public void button13_click1(GButton source, GEvent event) { //_CODE_:button13:879174:
  println("button13 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('7');
} //_CODE_:button13:879174:

public void button14_click1(GButton source, GEvent event) { //_CODE_:button14:903609:
  println("button14 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('g');
} //_CODE_:button14:903609:

public void button15_click1(GButton source, GEvent event) { //_CODE_:button15:319560:
  println("button15 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('8');
} //_CODE_:button15:319560:

public void button16_click1(GButton source, GEvent event) { //_CODE_:button16:705332:
  println("button16 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write('h');
} //_CODE_:button16:705332:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 100, 60, 80, 30);
  button1.setText("ON1");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 190, 60, 80, 30);
  button2.setText("OFF1");
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 100, 100, 80, 30);
  button3.setText("ON2");
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 190, 100, 80, 30);
  button4.setText("OFF2");
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(this, 100, 140, 80, 30);
  button5.setText("ON3");
  button5.addEventHandler(this, "button5_click1");
  button6 = new GButton(this, 190, 140, 80, 30);
  button6.setText("OFF3");
  button6.addEventHandler(this, "button6_click1");
  button7 = new GButton(this, 100, 180, 80, 30);
  button7.setText("ON4");
  button7.addEventHandler(this, "button7_click1");
  button8 = new GButton(this, 190, 180, 80, 28);
  button8.setText("OFF4");
  button8.addEventHandler(this, "button8_click1");
  button9 = new GButton(this, 100, 220, 80, 30);
  button9.setText("ON5");
  button9.addEventHandler(this, "button9_click1");
  button10 = new GButton(this, 190, 220, 80, 30);
  button10.setText("OFF5");
  button10.addEventHandler(this, "button10_click1");
  button11 = new GButton(this, 100, 260, 80, 30);
  button11.setText("ON6");
  button11.addEventHandler(this, "button11_click1");
  button12 = new GButton(this, 190, 260, 80, 30);
  button12.setText("OFF6");
  button12.addEventHandler(this, "button12_click1");
  button13 = new GButton(this, 100, 300, 80, 30);
  button13.setText("ON7");
  button13.addEventHandler(this, "button13_click1");
  button14 = new GButton(this, 190, 300, 80, 30);
  button14.setText("OFF7");
  button14.addEventHandler(this, "button14_click1");
  button15 = new GButton(this, 100, 340, 80, 30);
  button15.setText("ON8");
  button15.addEventHandler(this, "button15_click1");
  button16 = new GButton(this, 190, 340, 80, 30);
  button16.setText("OFF8");
  button16.addEventHandler(this, "button16_click1");
  label1 = new GLabel(this, 0, 0, 380, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Arduino + Processing Serial Control");
  label1.setTextBold();
  label1.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
GButton button5; 
GButton button6; 
GButton button7; 
GButton button8; 
GButton button9; 
GButton button10; 
GButton button11; 
GButton button12; 
GButton button13; 
GButton button14; 
GButton button15; 
GButton button16; 
GLabel label1; 